import { ReactRenderCallback, RegisterServiceWorker } from '@app/shared/types/function.types';

/**
 * The service worker will be generated by webpack workbox plugin, the service worker
 * file will be placed at the output directory, thus at the same level of index html.
 */
const registerServiceWorker: RegisterServiceWorker = async () =>
  navigator.serviceWorker.register('./service-worker.js');

/**
 * If in production mode and if the current browser has support for service workers,
 * add a listener for the load action to register it, otherwise do nothing.
 */
const serviceWorkerHook: ReactRenderCallback = () =>
  process.env.NODE_ENV === 'production' && 'serviceWorker' in navigator
    ? window.addEventListener('load', registerServiceWorker)
    : undefined;

export { serviceWorkerHook };
